locale                   : "en-US"
title                    : "Zhiyu Jiang / Personal Homepage"
title_separator          : "-"
name                     : &name "Zhiyu Jiang"
description              : &description "Academic website of Zhiyu Jiang, theoretical condensed matter physicist."
url                      : https://zhiyujiang1.github.io
baseurl                  : "/academicpages"
repository               : "ZhiyuJiang1/academicpages"

author:
  avatar                 : "Zhiyu Jiang.png"
  name                   : "Zhiyu Jiang"
  bio                    : "Appointed Researcher<br>Center for Quantum Information and Quantum Biology<br>The University of Osaka"
  location               : "Toyonaka, Osaka, Japan"
  employer               : "The University of Osaka"
  email                  : "jiang.zhiyu.qiqb@osaka-u.ac.jp"
  googlescholar          : "https://scholar.google.co.jp/citations?user=LpidLd4AAAAJ&hl=en"
  researchmap            : "https://researchmap.jp/zhiyu.jiang"
  orcid                  : "https://orcid.org/0009-0002-5485-2762"
  researchgate           : "https://www.researchgate.net/profile/Zhiyu-Jiang-12"

publication_category:
  books:
    title: "Books"
  manuscripts:
    title: "Journal Articles"
  conferences:
    title: "Conference Papers"

teaser                   :
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false

atom_feed:
  hide                   : false
  path                   :

analytics:
  provider               : false

include:
  - .htaccess
  - _pages
  - files

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - CHANGELOG
  - Capfile
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json*
  - Rakefile
  - README
  - tmp
  - vendor

keep_files:
  - .git
  - .svn

encoding                  : "utf-8"
markdown_ext              : "markdown,mkdown,mkdn,mkd,md"

markdown                  : kramdown
highlighter               : rouge
lsi                       : false
excerpt_separator         : "\n\n"
incremental               : false

kramdown:
  input                   : GFM
  hard_wrap               : false
  auto_ids                : true
  footnote_nr             : 1
  entity_output           : as_char
  toc_levels              : 1..6
  smart_quotes            : lsquo,rsquo,ldquo,rdquo
  enable_coderay          : false

collections:
  teaching:
    output                : true
    permalink             : /:collection/:path/
  publications:
    output                : true
    permalink             : /:collection/:path/
  awards:
    output                : true
    permalink             : /:collection/:path/
  talks:
    output                : true
    permalink             : /:collection/:path/

defaults:
  - scope:
      path                : ""
      type                : posts
    values:
      layout              : single
      author_profile      : true
      read_time           : true
      comments            : true
      share               : true
      related             : true
  - scope:
      path                : ""
      type                : pages
    values:
      layout              : single
      author_profile      : true
  - scope:
      path                : ""
      type                : teaching
    values:
      layout              : single
      author_profile      : true
      share               : true
      comments            : true
  - scope:
      path                : ""
      type                : publications
    values:
      layout              : single
      author_profile      : true
      share               : true
      comments            : true
  - scope:
      path                : ""
      type                : awards
    values:
      layout              : single
      author_profile      : true
      share               : true
      comments            : true
  - scope:
      path                : ""
      type                : talks
    values:
      layout              : talk
      author_profile      : true
      share               : true

sass:
  sass_dir                : _sass
  style                   : compressed

permalink                 : /:categories/:title/
timezone                  : Asia/Tokyo

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

category_archive:
  type                    : liquid
  path                    : /categories/

tag_archive:
  type                    : liquid
  path                    : /tags/

compress_html:
  clippings               : all
  ignore:
    envs                  : development
